---
title: "Old Faithful Eruptions"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r}
library(flexdashboard)
library(shiny)
library(shinydashboard)
library(dplyr)
```

Sidebar {.sidebar}
=======================================================================

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
```

Dashboard
=======================================================================

Row
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser Eruption Duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

Row
-----------------------------------------------------------------------

### Articles per Day {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = 11,
    icon = "fa-area-chart",
    color = "warning"
  )
})
```
```